name: ff
channels:
  - conda-forge
dependencies:
  - attrs=25.4.0
  - biopython=1.85
  - blosc=1.21.6
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.15.2
  - ca-certificates=2025.10.5
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - cyrus-sasl=2.1.28
  - deprecation=2.1.0
  - filelock=3.20.0
  - freetype=2.14.1
  - glew=2.1.0
  - glib=2.86.0
  - glib-tools=2.86.0
  - glm=1.0.1
  - gst-plugins-base=1.24.11
  - gstreamer=1.24.11
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - jinja2=3.1.6
  - joblib=1.5.2
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.9.1
  - krb5=1.21.3
  - libaec=1.1.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.8
  - libclang13=21.1.0
  - libcurl=8.16.0
  - libcxx=21.1.4
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libglib=2.86.0
  - libiconv=1.18
  - libintl=0.25.1
  - libintl-devel=0.25.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - libllvm18=18.1.8
  - libllvm21=21.1.0
  - liblzma=5.8.1
  - libnetcdf=4.9.2
  - libnghttp2=1.67.0
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopus=1.5.2
  - libpng=1.6.50
  - libpq=18.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libvorbis=1.3.7
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - llvm-openmp=21.1.4
  - lz4-c=1.10.0
  - markupsafe=3.0.3
  - mdtraj=1.10.3
  - narwhals=2.9.0
  - ncurses=6.5
  - nspr=4.37
  - nss=3.117
  - numexpr=2.14.1
  - numpy=2.2.6
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.46
  - pip=25.2
  - plotly=6.3.1
  - ply=3.11
  - pmw=2.0.1
  - pthread-stubs=0.4
  - py-cpuinfo=9.0.0
  - pymol-open-source=3.1.0
  - pyparsing=3.2.5
  - pyqt=5.15.11
  - pyqt5-sip=12.17.0
  - pytables=3.10.1
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - qt-main=5.15.15
  - readline=8.2
  - referencing=0.37.0
  - rpds-py=0.28.0
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - setuptools=80.9.0
  - signac=2.3.0
  - signac-flow=0.29.0
  - sip=6.14.0
  - six=1.17.0
  - snappy=1.2.2
  - synced_collections=1.0.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.3.0
  - tqdm=4.67.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxfixes=6.0.2
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstd=1.5.7
  - pip:
      - appnope==0.1.4
      - asttokens==3.0.0
      - comm==0.2.3
      - debugpy==1.8.17
      - decorator==5.2.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - fiberforge==0.1.0
      - ipykernel==7.0.1
      - ipython==8.37.0
      - jedi==0.19.2
      - jupyter-client==8.6.3
      - jupyter-core==5.9.1
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - parso==0.8.5
      - pexpect==4.9.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - psutil==7.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyzmq==27.1.0
      - stack-data==0.6.3
      - tornado==6.5.2
      - traitlets==5.14.3
      - wcwidth==0.2.14
